version: '3'
services:
  mysql:
    image: mysql:8
    container_name: dpd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: DPDAPI2025
      MYSQL_DATABASE: address_validator
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - ./database/simple_migration.sql:/docker-entrypoint-initdb.d/simple_migration.sql