CREATE TABLE addresses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    straße VARCHAR(255),
    haus_nummer VARCHAR(50),
    plz VARCHAR(20),
    stadt VARCHAR(100),
);

LOAD DATA INFILE '../ADRESSE.csv'
INTO TABLE table_name
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@ADRCD, @GKZ, @OKZ, @PLZ, @SKZ, @ZAEHLSPRENGEL, @HAUSNRTEXT, @HAUSNRZAHL1, @HAUSNRBUCHSTABE1, @HAUSNRVERBINDUNG1, @HAUSNRZAHL2, @HAUSNRBUCHSTABE2, @HAUSNRBEREICH, @HNR_ADR_ZUSAMMEN, @GNRADRESSE, @HOFNAME, @RW, @HW, @EPSG, @QUELLADRESSE, @BESTIMMUNGSART)  
SET 
    straße = @SKZ, 
    haus_nummer = concat(@HAUSNRTEXT @HAUSNRZAHL1, @HAUSNRBUCHSTABE1, @HAUSNRVERBINDUNG1, @HAUSNRZAHL2, @HAUSNRBUCHSTABE2, @HAUSNRBEREICH),
    plz = @PLZ,
    stadt = @SKZ;